### ISSUE TITLE
目标

### ISSUE THREAD

**Issue by knightXun** [knightXun/container-scheduler#1]
目前的调度系统的瓶颈主要在于存储，网络和算法．存储的瓶颈是原有etcd对缓存的处理不理想，网络可以自行调优，算法需要设计一套全新的数据结构和策略模型，本人在后期的测试过程中将视网络透明，不予考虑．此项目和本人的实际工作强相关，因此是一个长期的任务，预计在10月份发出release-1.0版本．目标是取代社区原生的调度系统，用于公司全新的PaaS平台．

**Comment by knightXun** [comment]
后期会综合waterpool进行一系列的实验

**Comment by nullnonenilNULL** [comment]
原版调度存在哪些问题呢，需要重新设计一个全新的调度系统？楼下的改进点在哪里呢？另外问下楼主release-1.0版有计划发出吗？

**Comment by knightXun** [comment]
haha,不好意思，天天加班，打算give up了，以后再说吧

**Comment by knightXun** [comment]
阁下肯定是故人，何必弄个小号来问我呢

**Comment by knightXun** [comment]
@nullnonenilNULL 阁下肯定是故人，何必弄个小号来问我呢

**Comment by nullnonenilNULL** [comment]
哈哈  大哥您想多了  这个真不是 没这么腹黑
